modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
modId="authforge"
version="1.1"
displayName="Example Mod"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://github.com/heipiao233/authforge"
logoFile="examplemod.png"
credits="Mojang, MCP, Forge"
authors="heipiao"
description='''
'''
[[dependencies.authforge]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.authforge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
