modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="authforge"
version="1.3"
displayName="锻造：认证"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://github.com/heipiao233/authforge"
logoFile="authforge.png"
credits="Mojang, MCP, Forge"
authors="heipiao"
description='''
你是想在打开局域网联机时需要密码才能加入吗（只有客户端才能看见）
'''
[[dependencies.authforge]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.authforge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"
